load_ckpt_teacher: /disk1/sosick377/cagc/results/training_03-20_08:40:02/network-snapshot-004233.pkl
load_ckpt_student: /disk1/sosick377/cagc_ckpt/pruned/0.7/pruned_network-0.7.pkl
save_ckpt: /disk1/sosick377/cagc_ckpt/training/ca0.7
data: /disk1/sosick377/datasets/ffhq256x256.zip
subset: # None: all
resume: # 추가하기

cond: False
num_gpus: 2 # number of GPUs
snap: 50 # snapshot interval
mirror: False


cfg: paper256 # auto, stylegan2, paper256, paper512, paper1024, cifar
metrics: ["fid50k_full"]
random_seed: 0
aug: noaug # None (ada), noaug, fixed
p: # Specify p for "fixed" (required): <float>

z_dim: 512
w_dim: 512
c_dim: 0




kd_method: ca # None: training, ca: content aware knowledge distillation
pruning_ratio: 0.7 # None: 0.0(dense)

### content aware pruning
n_sample: 400 # number of samples for estimation, default = 400
batch_size: 10 # size of the batch for estimation, default = 10
noise_prob: 0.05 # default = 0.05