load_ckpt: /disk1/sosick377/cagc/results/training_03-20_08:40:02/network-snapshot-004233.pkl
save_ckpt: /disk1/sosick377/cagc_ckpt/pruned/0.7

z_dim: 512
c_dim: 0

pruning_criterion: ca # ca: content aware pruning
pruning_ratio: 0.7 # default = 0.7

### content aware pruning
n_sample: 400 # number of samples for estimation, default = 400
batch_size: 10 # size of the batch for estimation, default = 10
noise_prob: 0.05 # default = 0.05