load_ckpt: /disk1/sosick377/content-aware-gan-compression/Model/full_size_model/256px_full_size.pt
save_ckpt:

z_dim: 512
c_dim: 0

pruning_criterion: ca # ca: content aware pruning
pruning_ratio: 0.7 # default = 0.7

### content aware pruning
n_sample: 20 # number of samples for estimation, default = 400
batch_size: 10 # size of the batch for estimation, default = 10
noise_prob: 0.05 # default = 0.05